# Generated by Django 3.0.5 on 2020-04-25 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombres')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='DNI')),
                ('date_joined', models.DateField(default=datetime.datetime(2020, 4, 25, 17, 34, 11, 8764), verbose_name='Fecha de registro')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de creación')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualización')),
                ('age', models.PositiveIntegerField(default=0)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('state', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d')),
                ('c_vitae', models.ImageField(blank=True, null=True, upload_to='c_vitae/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['-id'],
            },
        ),
    ]
