# Generated by Django 3.0.5 on 2020-04-25 22:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2020, 4, 25, 22, 37, 0, 572761, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
    ]
