# Generated by Django 3.0.5 on 2020-04-25 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20200425_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2020, 4, 25, 17, 37, 26, 355205), verbose_name='Fecha de registro'),
        ),
    ]
