# Generated by Django 3.0.5 on 2020-04-27 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20200427_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2020, 4, 27, 14, 35, 27, 200581), verbose_name='Fecha de registro'),
        ),
    ]
